name: terraform-apply

on:
  workflow_dispatch:
    inputs:
      pipeline_github_id:
        description: 'GitHub Run ID which triggered the pipeline'
        required: true
      model_version:
        description: 'SageMaker Model Version'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/rahul-mlops-github-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.x

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ./terraform/deployment

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
        working-directory: ./terraform/deployment
        env:
          TF_VAR_model_version: ${{ inputs.model_version }}
          TF_VAR_github_run_id: ${{ inputs.pipeline_github_id }}
          TF_VAR_environment: dev

      - name: Terraform Apply
        # if: ${{ github.ref == 'refs/heads/master' }}
        run: terraform apply -input=false -auto-approve tfplan
        working-directory: ./terraform/deployment
        env:
          TF_VAR_model_version: ${{ inputs.model_version }}
          TF_VAR_github_run_id: ${{ inputs.pipeline_github_id }}
          TF_VAR_environment: dev

      - run: aws sagemaker update-model-package --model-package-arn 'arn:aws:sagemaker:us-east-1:${{ vars.AWS_ACCOUNT_ID }}:model-package/rahul-mlops-model-package-group/${{ inputs.model_version }}' --region 'us-east-1' --model-life-cycle '{"Stage":"Development", "StageStatus":"Approved"}'


