name: start-pipeline-execution

on:
  push:
    branches: ["code-test"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: |
         echo "::add-mask::${{ vars.AWS_ACCOUNT_ID }}"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/rahul-github-role 
          aws-region: us-east-1

      - run: aws sagemaker list-pipeline-executions --pipeline-name rahul-mlops-pipeline | jq '.PipelineExecutionSummaries | length'

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Patch SageMaker dependencies
        run: |
          source .venv/bin/activate
          sed -i "s/dependencies = source_code.dependencies/dependencies = []/" \
              .venv/lib/python3.12/site-packages/sagemaker/core/workflow/utilities.py

      - name: Start Pipeline Execution
        run: |
          source .venv/bin/activate
          python3 ./pipeline/pipeline.py --data-s3-uri s3://rahul-mlops-data-bucket/cleaned_data/spam.csv --gh-run-id ${{ github.run_id }} --environment dev
